### PR TITLE
[0.24] KafkaChannel to init offsets before dispatcher 

### LINKED ISSUE #549: [Consolidated Channel] events potentially undelivered if kafka-ch-dispatcher restarted before first events sent
**Describe the bug**

In a following scenario:
1. Subscription to a KafkaChannel gets Ready
2. kafka-ch-disptacher is restarted (e.g. pod delete)
3. events are sent just as new kafka-ch-disptacher starts

Some of the first events are not delivered to the subscriber.

It seems that if no events were yet commited, the new kafka-ch-dispatcher starts partition consumers at the "-1" offset, even if the subscription was already Ready before.

```
{"level":"info","ts":"2021-04-18T08:05:05.639Z","logger":"kafkachannel-dispatcher","caller":"consumer/consumer_handler.go:76","msg":"Starting partition consumer, topic: knative-messaging-kafka.foobar.channel-eupfwclx, partition: 0, initialOffset: -1","knative.dev/pod":"kafka-ch-dispatcher-5dbdb9bc75-z9xsx","ConsumeGroup":"kafka.foobar.channel-eupfwclx.6231d7a9-9741-4a5c-9cd6-91b7e2fbe64e"}
```

It should probably start at "0" in that case?

 **Expected behavior**
Events should be delivered even if kafka-ch-dispatcher was restarted just before first events were sent

 **To Reproduce**
Steps to reproduce the behavior.

Reproducer: https://github.com/maschmid/kafkachannel-subscription-ready-before-partition-consumers-started ( specifically TestDispatcherRestartBeforeCommitedEvents )

```
make apply
go test -v -run TestDispatcherRestartBeforeCommitedEvents
```

 **Knative release version**
0.20

 **Additional context**
Reproduced on OCP 4.7.6, knative installed with Serverless Operator, with Kafka installed on the OCP cluster with Strimzi.

### PR DESCRIPTION
**Pull request by aliok**
Fixes #549

## Proposed Changes

- Init offsets, similar to KafkaSource, to make sure dispatcher doesn't fetch events from latest when it starts (more details on the issue)
- Consumer groups are now started after making sure the initial offsets are committed by the controller(s)
- **NOTE**: Check for the initial offsets are done in the ConsumerFactory. This means, KafkaSource adapters and distributed channel **can** get this functionality for free. However, I didn't enable it for them.
- Get rid of status probing mechanism for subscription readiness in Kafka Channel
- Needed to touch some `distributed` channel code as I changed some interfaces. But, no business logic changes

**Release Note**

```release-note
- 🐛  Fixed a bug that was causing Kafka Channel dispatcher to miss some events in case the offset for the consumer group was not initialized
```

**Docs**

### CODE REVIEW

**Comment by aliok** [comment]
/retest

Wtf

**Comment by aliok** [comment]
/retest

Let's see what happens

File: pkg/channel/consolidated/reconciler/controller/kafkachannel.go [hunk 1]
```diff
@@ -477,7 +492,20 @@ func (r *Reconciler) reconcileChannelService(ctx context.Context, dispatcherName
 	return svc, nil
 }
 
-func (r *Reconciler) createClient(ctx context.Context) (sarama.ClusterAdmin, error) {
+func (r *Reconciler) createClients(ctx context.Context) (sarama.Client, sarama.ClusterAdmin, error) {
+	kafkaClient := r.kafkaClient
```
Comment (devguyio) [inline pkg/channel/consolidated/reconciler/controller/kafkachannel.go:496]: you're not setting 
`r.kafkaClient` anywhere, is that intentional? wouldn't that mean you're creating a new client with every reconcile loop?

File: pkg/channel/consolidated/reconciler/controller/kafkachannel.go [hunk 2]
```diff
@@ -249,12 +250,26 @@ func (r *Reconciler) ReconcileKind(ctx context.Context, kc *v1beta1.KafkaChannel
 	return newReconciledNormal(kc.Namespace, kc.Name)
 }
 
-func (r *Reconciler) reconcileSubscribers(ctx context.Context, ch *v1beta1.KafkaChannel) error {
+func (r *Reconciler) reconcileSubscribers(ctx context.Context, ch *v1beta1.KafkaChannel, kafkaClient sarama.Client, kafkaClusterAdmin sarama.ClusterAdmin) error {
 	after := ch.DeepCopy()
 	after.Status.Subscribers = make([]v1.SubscriberStatus, 0)
+	logger := logging.FromContext(ctx)
 	for _, s := range ch.Spec.Subscribers {
```
Comment (devguyio) [inline pkg/channel/consolidated/reconciler/controller/kafkachannel.go:257]: A good optimization once we get this working is to do this only for the diff between `ch.Spec.Subscribers` and ready ones of `ch.Status.Subscribers` . Cause now with the smallest change in the channel, you're hitting kafka with api calls for every single subscription. 

Or in `reconcileInitialOffset` you can check if the sub is not ready then initialize the offsets.

**Review by devguyio — COMMENTED** [review]
I did a short review, will continue later today.

File: pkg/channel/consolidated/reconciler/controller/kafkachannel.go (hunk 1 above)
Comment (aliok) [reply pkg/channel/consolidated/reconciler/controller/kafkachannel.go:496]: I refactored the code that creates the admin client and created the normal client there.

For clusterAdmin, there's this ticket: https://github.com/Shopify/sarama/issues/1162. I see that ticket didn't really get any resolution.

I haven't tried reusing the regular kafkaClient. I can try that, once I made the failing tests working.

**Comment by aliok** [comment]
/test pull-knative-sandbox-eventing-kafka-integration-test-channel-consolidated

Retesting to see if there's a pattern

File: pkg/channel/consolidated/reconciler/controller/controller.go [hunk 3]
```diff
@@ -174,22 +159,23 @@ func NewController(
 			knativeReconciler.LabelFilterFunc(roleLabelKey, dispatcherRoleLabelValue, false),
 		),
 		Handler: cache.ResourceEventHandlerFuncs{
-			// Cancel probing when a Pod is deleted
-			DeleteFunc: getPodInformerEventHandler(ctx, logger, statusProber, impl, kafkaChannelInformer, "Delete"),
-			AddFunc:    getPodInformerEventHandler(ctx, logger, statusProber, impl, kafkaChannelInformer, "Add"),
+			// TODO: do we still need this?
+			// Global sync when a Pod is deleted or added
+			DeleteFunc: getPodInformerEventHandler(ctx, logger, impl, kafkaChannelInformer, "Delete"),
+			AddFunc:    getPodInformerEventHandler(ctx, logger, impl, kafkaChannelInformer, "Add"),
```
Comment (matzew) [inline pkg/channel/consolidated/reconciler/controller/controller.go:165]: It was introduced as a change on top of adding the prober... which we now remove, hence I _think_ we can remove the hndler here

File: pkg/channel/consolidated/reconciler/controller/kafkachannel.go (hunk 1 above)
Comment (matzew) [reply pkg/channel/consolidated/reconciler/controller/kafkachannel.go:496]: pretty bad sarama bug :disappointed:

File: pkg/channel/consolidated/reconciler/controller/kafkachannel.go (hunk 2 above)
Comment (matzew) [reply pkg/channel/consolidated/reconciler/controller/kafkachannel.go:257]: I think I like the suggestion for doing the check inside the `reconcileInitialOffset`

File: pkg/common/consumer/consumer_factory.go [hunk 4]
```diff
@@ -64,11 +72,38 @@ func (c *customConsumerGroup) Close() error {
...
+	defer clusterAdmin.Close()
+
+	// this is a blocking func
+	// do not proceed until the check is done
+	err = c.kcoi.checkOffsetsInitialized(ctx, groupID, topics, logger, client, clusterAdmin)
 	if err != nil {
 		return nil, err
 	}
+
+	logger.Infow("All offsets are initialized", zap.Any("topics", topics), zap.Any("groupID", groupID))
```
Comment (matzew) [inline pkg/common/consumer/consumer_factory.go:105]: do we really want this info?

File: pkg/common/consumer/consumer_offset_initalizer.go [hunk 5]
```diff
@@ -0,0 +1,43 @@
...
+	"context"
+	"fmt"
+
+	"github.com/Shopify/sarama"
+	"go.uber.org/zap"
+	"k8s.io/apimachinery/pkg/util/wait"
+	"knative.dev/eventing-kafka/pkg/common/kafka/offset"
+)
+
+type consumerOffsetInitializer interface {
```
Comment (devguyio) [inline pkg/common/consumer/consumer_offset_initalizer.go:13]: 1. this name gives me the indication that it is an "initializer" , while it's actually only checking.
2. consumer is not a consumer group. 

So maybe rename it to something like "CGOffsetsMonitor" or something like that, "Poller" , "Checker" .

File: pkg/common/kafka/offset/offsets.go [hunk 6]
```diff
@@ -101,3 +93,61 @@ func InitOffsets(ctx context.Context, kafkaClient sarama.Client, kafkaAdminClien
...
+	// Retrieve all partitions
+	topicPartitions := make(map[string][]int32)
+	for _, topic := range topics {
+		partitions, err := kafkaClient.Partitions(topic)
+		totalPartitions += len(partitions)
+		if err != nil {
+			return -1, nil, fmt.Errorf("failed to get partitions for topic %s: %w", topic, err)
+		}
+
+		topicPartitions[topic] = partitions
```
Comment (devguyio) [inline pkg/common/kafka/offset/offsets.go:150]: I think it's safer to assign a copy of the partitions slice instead of using the one returned by the client (I traced the code, it's cached in Sarama so I think we should play it safe and just copy it here)

File: pkg/common/kafka/offset/offsets.go [hunk 7]
```diff
@@ -101,3 +93,61 @@ func InitOffsets(ctx context.Context, kafkaClient sarama.Client, kafkaAdminClien
...
+	}
+
+	for topic, partitions := range offsets.Blocks {
+		for partitionID, block := range partitions {
+			if block.Offset == -1 { // not initialized?
+				partitionsOffsets, ok := topicOffsets[topic]
+				if !ok {
+					// topic may have been deleted. ignore.
+					continue
+				}
```
Comment (devguyio) [inline pkg/common/kafka/offset/offsets.go:122]: Why are you handling this case here? why can't it just focus on the offsets, and if it's not there then `CheckIfAllOffsetsInitialized` returns simply false. (i.e. this function assuming that topics exists, and leaves it up to the caller to only call it for topics that exist)  I feel this is too much assumption here (that if the topic is deleted then that's ok)

**Review by devguyio — COMMENTED** [review]
Round two, wanna send the comments in batches.

File: pkg/common/kafka/offset/offsets.go [hunk 8]
```diff
@@ -101,3 +93,61 @@ func InitOffsets(ctx context.Context, kafkaClient sarama.Client, kafkaAdminClien
...
+
+				_, ok = partitionsOffsets[partitionID]
+				if !ok {
+					// partition may have been deleted. ignore.
+					continue
+				}
+
+				return false, nil
```
Comment (devguyio) [inline pkg/common/kafka/offset/offsets.go:130]: same as above

File: pkg/common/kafka/offset/offsets.go (hunk 7 above)
Comment (devguyio) [reply pkg/common/kafka/offset/offsets.go:122]: I just noticed this is the same logic for the `InitOffset` method. Still wondering why we need to have it though.

File: pkg/channel/consolidated/reconciler/controller/controller.go (hunk 3 above)
Comment (aliok) [reply pkg/channel/consolidated/reconciler/controller/controller.go]: Done

File: pkg/common/consumer/consumer_factory.go (hunk 4 above)
Comment (aliok) [reply pkg/common/consumer/consumer_factory.go]: Changed to debug

File: pkg/common/consumer/consumer_offset_initalizer.go [hunk 9]
```diff
@@ -0,0 +1,43 @@
...
+	checkOffsetsInitialized(ctx context.Context, groupID string, topics []string, logger *zap.SugaredLogger, client sarama.Client, clusterAdmin sarama.ClusterAdmin) error
```
[the remark this answers is not in the document]
Comment (aliok) [reply pkg/common/consumer/consumer_offset_initalizer.go]: Thanks, renamed to `ConsumerGroupOffsetsChecker`

File: pkg/common/consumer/consumer_factory.go [hunk 10]
```diff
@@ -19,25 +19,33 @@ package consumer
...
+	"time"
 
 	"github.com/Shopify/sarama"
 	"go.uber.org/zap"
+	"knative.dev/pkg/logging"
 )
 
-// newConsumerGroup is a wrapper for the Sarama NewConsumerGroup function, to facilitate unit testing
+const OffsetInitRetryTimeout = 60 * time.Second
+const OffsetInitRetryInterval = 5 * time.Second
```
[the remark this answers is not in the document]
Comment (aliok) [reply pkg/common/consumer/consumer_factory.go]: Done, thanks

File: pkg/common/consumer/consumer_offset_initalizer.go (hunk 5 above)
Comment (aliok) [reply pkg/common/consumer/consumer_offset_initalizer.go]: LOL, you're right. I was also doing the offset initialization inside this interface but then didn't think about the changing the name.

It is changed now.

File: pkg/common/kafka/offset/offsets.go (hunk 7 above)
Comment (aliok) [reply pkg/common/kafka/offset/offsets.go]: @lionelvillard told me that we won't need to handle the deleted topic and partitions too in the check function. I deleted that code now.

He can maybe give more info on why we need to handle these cases in the `initoffsets` function.

File: pkg/common/kafka/offset/offsets.go (hunk 6 above)
Comment (aliok) [reply pkg/common/kafka/offset/offsets.go]: well this function is only used in this file and we certainly do not modify the array. ...but, let's play safe as you said for future generations.
This is done.

**Comment by aliok** [comment]
cc @lionelvillard @devguyio 
PR is ready.

Also cc @travis-minke-sap . I haven't made any business logic change in any components other than the consolidated channel.

**Comment by matzew** [comment]
Just tested

```
Receiving duration has passed!
Total received message count: 5455
Latest message index: 5455
Missing messages count: 0
Missing messages: 
Duplicate messages: {}
```

:tada: 

will now review 

/assign @matzew

File: pkg/channel/consolidated/reconciler/controller/kafkachannel.go [hunk 11]
```diff
@@ -578,7 +622,7 @@ func (r *Reconciler) FinalizeKind(ctx context.Context, kc *v1beta1.KafkaChannel)
 	logger := logging.FromContext(ctx)
 	channel := fmt.Sprintf("%s/%s", kc.GetNamespace(), kc.GetName())
 	logger.Debugw("FinalizeKind", zap.String("channel", channel))
-	kafkaClusterAdmin, err := r.createClient(ctx)
+	_, kafkaClusterAdmin, err := r.createClients(ctx)
```
Comment (devguyio) [inline pkg/channel/consolidated/reconciler/controller/kafkachannel.go:625]: you probably wanna capture the kafkaClient here and defere closing it

File: pkg/common/consumer/consumer_factory.go [hunk 12]
```diff
@@ -64,13 +66,17 @@ func (c *customConsumerGroup) Close() error {
 var _ sarama.ConsumerGroup = (*customConsumerGroup)(nil)
 
 // StartConsumerGroup creates a new customConsumerGroup and starts a Consume goroutine on it
-func (c kafkaConsumerGroupFactoryImpl) StartConsumerGroup(groupID string, topics []string, logger *zap.SugaredLogger, handler KafkaConsumerHandler, options ...SaramaConsumerHandlerOption) (sarama.ConsumerGroup, error) {
+func (c kafkaConsumerGroupFactoryImpl) StartConsumerGroup(ctx context.Context, groupID string, topics []string, handler KafkaConsumerHandler, options ...SaramaConsumerHandlerOption) (sarama.ConsumerGroup, error) {
+	logger := logging.FromContext(ctx)
+
 	consumerGroup, err := c.createConsumerGroup(groupID)
 	if err != nil {
+		logger.Errorw("Unable to create consumer group", zap.Error(err))
```
Comment (devguyio) [inline pkg/common/consumer/consumer_factory.go:74]: NIT: error message starting with lower case

File: pkg/common/consumer/consumergroup_offsets_checker.go [hunk 13]
```diff
@@ -0,0 +1,74 @@
...
+
+type KafkaConsumerGroupOffsetsChecker struct {
+}
+
+func (k *KafkaConsumerGroupOffsetsChecker) WaitForOffsetsInitialization(ctx context.Context, groupID string, topics []string, logger *zap.SugaredLogger, addrs []string, config *sarama.Config) error {
+	logger.Infow("Checking if all offsets are initialized", zap.Any("topics", topics), zap.Any("groupID", groupID))
+
+	client, err := newSaramaClient(addrs, config)
+	if err != nil {
+		logger.Errorw("Unable to create Kafka client", zap.Error(err))
```
Comment (devguyio) [inline pkg/common/consumer/consumergroup_offsets_checker.go:42]: 1. NIT error message starting with lower case
1. would be helpful to add the groupID and topics

File: pkg/channel/consolidated/reconciler/controller/kafkachannel.go [hunk 14]
```diff
@@ -249,12 +250,26 @@ func (r *Reconciler) ReconcileKind(ctx context.Context, kc *v1beta1.KafkaChannel
...
 	after.Status.Subscribers = make([]v1.SubscriberStatus, 0)
+	logger := logging.FromContext(ctx)
 	for _, s := range ch.Spec.Subscribers {
-		if r, _ := r.statusManager.IsReady(ctx, *ch, s); r {
-			logging.FromContext(ctx).Debugw("marking subscription", zap.Any("subscription", s))
+		logger.Debugw("Reconciling initial offset for subscription", zap.Any("subscription", s))
+		err := r.reconcileInitialOffset(ctx, ch, s, kafkaClient, kafkaClusterAdmin)
+
+		if err != nil {
+			logger.Errorw("Reconcile failed fo initial offset for subscription", zap.Any("subscription", s), zap.Error(err))
```
Comment (travis-minke-sap) [inline pkg/channel/consolidated/reconciler/controller/kafkachannel.go:262]: Typo `failed fo initial`

File: pkg/common/consumer/consumergroup_offsets_checker.go [hunk 15]
```diff
@@ -0,0 +1,74 @@
...
+		return err
+	}
+	defer client.Close()
+
+	clusterAdmin, err := newSaramaClusterAdmin(addrs, config)
+	if err != nil {
+		logger.Errorw("Unable to create Kafka cluster admin client", zap.Error(err))
```
Comment (devguyio) [inline pkg/common/consumer/consumergroup_offsets_checker.go:49]: same as above

File: pkg/common/consumer/consumergroup_offsets_checker.go [hunk 16]
```diff
@@ -0,0 +1,74 @@
...
+	check := func() (bool, error) {
+		if initialized, err := offset.CheckIfAllOffsetsInitialized(client, clusterAdmin, topics, groupID); err == nil {
+			if initialized {
+				return true, nil
+			} else {
+				logger.Infow("Offsets not yet initialized, going to try again")
+				return false, nil
+			}
+		} else {
+			return true, fmt.Errorf("error checking if offsets are initialized. stopping trying. %w", err)
```
Comment (devguyio) [inline pkg/common/consumer/consumergroup_offsets_checker.go:63]:
```suggestion
			return false, fmt.Errorf("error checking if offsets are initialized. stopping trying. %w", err)
```

I think this is the correct behavior when you want to stop retrying in the error case. `PollUntil` will stop when there's an error

File: pkg/common/consumer/consumer_factory.go [hunk 17]
```diff
@@ -94,6 +101,16 @@ func (c kafkaConsumerGroupFactoryImpl) startExistingConsumerGroup(
 	ctx, cancel := context.WithCancel(context.Background())
 
 	go func() {
+		// this is a blocking func
+		// do not proceed until the check is done
+		err := c.offsetsChecker.WaitForOffsetsInitialization(ctx, groupID, topics, logger, c.addrs, c.config)
+		if err != nil {
+			logger.Errorw("Error while checking if offsets are initialized", zap.Error(err))
```
Comment (devguyio) [inline pkg/common/consumer/consumer_factory.go:108]: 1. NIT error message starting with lowercase 
2. useful to add groupID and topics

**Review by devguyio — COMMENTED** [review]
halfway through, submitting those and will continue

**Comment by devguyio** [comment]
I left some comments above,
other than those it LGTM
nice work @aliok !!! 🎉

**Comment by travis-minke-sap** [comment]
> Also cc @travis-minke-sap . I haven't made any business logic change in any components other than the consolidated channel.

Thanks for the heads-up Ali!

In general I'm ok with the approach, and the way you've allowed the distributed channel to NoOp seems fine.  Is there any reason the distributed channel wouldn't want to do this same initial offset committing?  I'm thinking I can create a separate Issue to add it to the distributed channel's dispatcher on `main/` once you get these changes up there?

File: pkg/channel/consolidated/reconciler/controller/kafkachannel.go [hunk 18]
```diff
@@ -249,12 +250,26 @@ func (r *Reconciler) ReconcileKind(ctx context.Context, kc *v1beta1.KafkaChannel
...
+			logger.Errorw("marking subscription unready", zap.Any("subscription", s))
```
[the remark this answers is not in the document]
Comment (matzew) [reply pkg/channel/consolidated/reconciler/controller/kafkachannel.go:263]: > error logs start with lower case.

I think serving/eventing are doing it with Uppercase.  E.g.:
* https://github.com/knative/eventing/blob/c820f4239730dacf5b2e0e5eed67a496bdc9b424/pkg/reconciler/apiserversource/apiserversource.go#L103
* https://github.com/knative/serving/blob/67429ed977913af216d28245fe24cbf326659538/cmd/queue/main.go#L248


As well +1 on adding the channel for debugging

[the remark this answers is not in the document]
Comment (matzew) [reply pkg/channel/consolidated/reconciler/controller/kafkachannel.go:263]: ah... now I understand. With `error logs start with lower case.` you mean they are incorrectly starting with lowercase :smile:

File: pkg/common/consumer/consumer_factory.go (hunk 12 above)
Comment (matzew) [reply pkg/common/consumer/consumer_factory.go:74]: hrm - not sure what you mean here

File: pkg/common/consumer/consumergroup_offsets_checker.go (hunk 13 above)
Comment (matzew) [reply pkg/common/consumer/consumergroup_offsets_checker.go:42]: > NIT error message starting with lower case

the `Unable to create Kafka client` is starting with upper case... which is correct? :thinking:

File: pkg/channel/consolidated/reconciler/controller/kafkachannel.go (hunk 18 above)
[the remark this answers is not in the document]
Comment (matzew) [reply pkg/channel/consolidated/reconciler/controller/kafkachannel.go:263]: looking at the other entries, regarding "lowercase", I am actually not sure

File: pkg/common/consumer/consumergroup_offsets_checker.go (hunk 16 above)
Comment (matzew) [reply pkg/common/consumer/consumergroup_offsets_checker.go:63]: I agree here too.  I'd also give a little comment above the  `	check := func() (bool, error)...` regarding this, and meanings

File: pkg/common/consumer/consumergroup_offsets_checker.go [hunk 19]
```diff
@@ -0,0 +1,74 @@
...
+
+func (c *NoopConsumerGroupOffsetsChecker) WaitForOffsetsInitialization(ctx context.Context, groupID string, topics []string, logger *zap.SugaredLogger, addrs []string, config *sarama.Config) error {
+	return nil
+}
+
+type KafkaConsumerGroupOffsetsChecker struct {
+}
+
+func (k *KafkaConsumerGroupOffsetsChecker) WaitForOffsetsInitialization(ctx context.Context, groupID string, topics []string, logger *zap.SugaredLogger, addrs []string, config *sarama.Config) error {
+	logger.Infow("Checking if all offsets are initialized", zap.Any("topics", topics), zap.Any("groupID", groupID))
```
Comment (matzew) [inline pkg/common/consumer/consumergroup_offsets_checker.go:38]: should this be really Info?

File: pkg/common/consumer/consumergroup_offsets_checker.go [hunk 20]
```diff
@@ -0,0 +1,74 @@
...
+		return err
+	}
+	defer clusterAdmin.Close()
+
+	check := func() (bool, error) {
+		if initialized, err := offset.CheckIfAllOffsetsInitialized(client, clusterAdmin, topics, groupID); err == nil {
+			if initialized {
+				return true, nil
+			} else {
+				logger.Infow("Offsets not yet initialized, going to try again")
```
Comment (matzew) [inline pkg/common/consumer/consumergroup_offsets_checker.go:59]: I'd prob. also do this to debug - to reduce the noise?

File: pkg/channel/consolidated/reconciler/controller/kafkachannel.go (hunk 1 above)
Comment (matzew) [reply pkg/channel/consolidated/reconciler/controller/kafkachannel.go:496]: Can we add a comment that this thing returns both clients? Normal and ClusterAdmin?

`func (r *Reconciler) createSaramaClients` instead?  not just client?

Comment (matzew) [reply pkg/channel/consolidated/reconciler/controller/kafkachannel.go:496]: Do we really always need _both_?  See Ahmed's comment with stashing and defering the "regular" client.

Just wondering

File: pkg/common/consumer/consumergroup_offsets_checker.go (hunk 16 above)
Comment (aliok) [reply pkg/common/consumer/consumergroup_offsets_checker.go:63]:
```
PollUntil tries a condition func until it returns true, an error or stopCh is closed.
```

So, it won't matter if it is returning `true,err` or `false,err` as long as there's an error.

File: pkg/channel/consolidated/reconciler/controller/kafkachannel.go (hunk 1 above)
Comment (devguyio) [reply pkg/channel/consolidated/reconciler/controller/kafkachannel.go:494]: one alternative can be that we have two functions, one for each.

File: pkg/common/consumer/consumer_factory.go (hunk 12 above)
Comment (devguyio) [reply pkg/common/consumer/consumer_factory.go]: I mean something like
```go
logger.Errorw("Unable to create consumer group", zap.Error(err), zap.Sting("Consumer Group", groupID))
```

File: pkg/common/consumer/consumergroup_offsets_checker.go (hunk 16 above)
Comment (devguyio) [reply pkg/common/consumer/consumergroup_offsets_checker.go]: There's a difference in the semantic meaning, returning `true, nil` means the check succeeded, stop retrying, returning `false, err` means the check failed with an error, stop retrying. 

Reading in the corde `true, err` is confusing knowing the semantic meaning behind it.

**Comment by aliok** [comment]
> In general I'm ok with the approach, and the way you've allowed the distributed channel to NoOp seems fine. Is there any reason the distributed channel wouldn't want to do this same initial offset committing? I'm thinking I can create a separate Issue to add it to the distributed channel's dispatcher on main/ once you get these changes up there?

@travis-minke-sap 

Distributed channel can also do the same thing. I don't see any reason.
There are 2 steps:
- Committing the initial offsets in the channel controller using `offset.InitOffsets`
- Not starting consuming messages in the dispatcher until checking if the offsets are committed using `offset.CheckIfAllOffsetsInitialized`

I am going to forward port this PR all the way to the main. I don't think I would have the chance to implement it for distributed channel but at least there would be something in main in the consolidated channel that can be leveraged.

File: pkg/common/consumer/consumergroup_offsets_checker.go (hunk 16 above)
Comment (aliok) [reply pkg/common/consumer/consumergroup_offsets_checker.go]: Ok, changed it anyway

File: pkg/channel/consolidated/reconciler/controller/kafkachannel.go (hunk 1 above)
Comment (aliok) [reply pkg/channel/consolidated/reconciler/controller/kafkachannel.go:502]: We now have 2 functions. Code looks much better, thanks for the suggestions.

About stashing into `r.kafkaClient` -> I will try this, one I see tests are passing again.

**Comment by aliok** [comment]
/test pull-knative-sandbox-eventing-kafka-integration-test-channel-consolidated
/test pull-knative-sandbox-eventing-kafka-integration-test-channel-consolidated-sasl
/test pull-knative-sandbox-eventing-kafka-integration-test-channel-consolidated-tls

Stashing the kafka client broke things. I am gonna try here again, before reverting commit 4d57547.

File: pkg/channel/consolidated/reconciler/controller/kafkachannel.go (hunk 1 above)
Comment (aliok) [reply pkg/channel/consolidated/reconciler/controller/kafkachannel.go]: Ok, when I stash the client to `r.kafkaClient` and reuse it, things break. I have no desire to debug why.

See my comment here: https://github.com/knative-sandbox/eventing-kafka/pull/886#issuecomment-932092014

You can have a look at the commit list here, https://github.com/knative-sandbox/eventing-kafka/pull/886/commits, and see the job history for each commit there (not always consistent, especially when there's new code pushed while the jobs were running).

**Comment by aliok** [comment]
> Stashing the kafka client broke things. I am gonna try here again, before reverting commit 4d57547.

I reverted it now. See my comment here: https://github.com/knative-sandbox/eventing-kafka/pull/886#discussion_r720128806

File: pkg/channel/consolidated/reconciler/controller/kafkachannel.go (hunk 2 above)
Comment (aliok) [reply pkg/channel/consolidated/reconciler/controller/kafkachannel.go:265]: Done now

**Comment by aliok** [comment]
/test pull-knative-sandbox-eventing-kafka-unit-tests

TestEnableSaramaLogging

File: pkg/channel/consolidated/reconciler/controller/kafkachannel.go (hunk 1 above)
Comment (matzew) [reply pkg/channel/consolidated/reconciler/controller/kafkachannel.go:502]: > . I have no desire to debug why.

that is OK w/ me. That said - mind creating an issue we are having to track this?

Comment (aliok) [reply pkg/channel/consolidated/reconciler/controller/kafkachannel.go:502]: https://github.com/knative-sandbox/eventing-kafka/issues/912
