### PR TITLE
Make sure ConsumeClaim exit before rebalance.timeout

### LINKED ISSUE #629: Duplicate messages when adapter/dispatcher failed to drain messages "on time"
**Describe the bug**
When a Kafka source spans over one pod, we receive duplicate messages 

 **Expected behavior**
When a Kafka source spans over one pod, we should not receive dups. 

 **To Reproduce**
Create a Kafka source that spans over multiple adapter pod, you should see duplicate messages in the sink. 

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

### PR DESCRIPTION
**Pull request by lionelvillard**
Fixes #629

## Proposed Changes

-  Cancel dispatching messages when consumer group session is closed 

**Release Note**

```release-note
- 🐛Fix a bug in consolidate channel where deleting a KafkaChannel-backed Broker with events in flight blocks new subscriptions in SubscriptionNotMarkedReadyByChannel . 
- 🐛Fix a bug in KafkaSource potentially sending duplicates when Kafka rebalancing occurs
```

**Docs**

### CODE REVIEW

File: pkg/common/consumer/consumer_handler.go [hunk 1]
```diff
@@ -131,7 +153,7 @@ func (consumer *SaramaConsumerHandler) ConsumeClaim(session sarama.ConsumerGroup
 		if mustMark {
 			session.MarkMessage(message, "") // Mark kafka message as processed
 			if ce := consumer.logger.Desugar().Check(zap.DebugLevel, "debugging"); ce != nil {
-				consumer.logger.Debugw("Message marked", zap.String("topic", message.Topic), zap.Binary("value", message.Value))
+				consumer.logger.Infow("Message marked", zap.String("topic", message.Topic), zap.Binary("value", message.Value))
```
Comment (matzew) [inline pkg/common/consumer/consumer_handler.go:156]: Do we really want to bubble that up as Info?  Isn't that to verbose?

File: pkg/common/consumer/consumer_handler.go [hunk 2]
```diff
@@ -141,4 +163,13 @@ func (consumer *SaramaConsumerHandler) ConsumeClaim(session sarama.ConsumerGroup
 	return nil
 }
 
+func sessionClosed(session sarama.ConsumerGroupSession) bool {
+	select {
+	case <-session.Context().Done():
```
Comment (slinkydeveloper) [inline pkg/common/consumer/consumer_handler.go:168]: you can use just `Context().Err() != nil`

File: pkg/common/consumer/consumer_handler.go (hunk 1 above)
Comment (lionelvillard) [reply pkg/common/consumer/consumer_handler.go:156]: oh I didn't mean to change that. Thanks! fixing

File: pkg/common/consumer/consumer_handler.go [hunk 3]
```diff
@@ -113,14 +124,25 @@ func (consumer *SaramaConsumerHandler) ConsumeClaim(session sarama.ConsumerGroup
...
 	for message := range claim.Messages() {
-
 		if ce := consumer.logger.Desugar().Check(zap.DebugLevel, "debugging"); ce != nil {
 			consumer.logger.Debugw("Message claimed", zap.String("topic", message.Topic), zap.Binary("value", message.Value))
 		}
 
-		// Don't use the session context since it is closed before messages are drained.
-		// Handle must finish before the session timeout.
-		mustMark, err := consumer.handler.Handle(context.Background(), message)
+		// Preemptively interrupt processing messages if the session is closed.
```
Comment (matzew) [inline pkg/common/consumer/consumer_handler.go:131]: closed sessions due to a specific reason?

**Review by slinkydeveloper — COMMENTED** [review]
LGTM, just left a minor style comment

**Comment by devguyio** [comment]
/assign
I'm working on a very similar issue, lemme check it out on my problem before merging

File: pkg/common/consumer/consumer_handler.go [hunk 4]
```diff
@@ -113,14 +124,25 @@ func (consumer *SaramaConsumerHandler) ConsumeClaim(session sarama.ConsumerGroup
...
+		if sessionClosed(session) {
+			consumer.logger.Infof("Session closed for %s/%d. Exiting ConsumeClaim ", claim.Topic(), claim.Partition())
+			break
+		}
+
+		// Don't use the session context because when cancelled it will interrupt the in-flight request,
+		// potentially leading to duplicates
+
+		// Handle must finish before the session timeout. Enforcing it on the client side.
+		ctx, cancel := context.WithTimeout(context.Background(), consumer.timeout)
```
Comment (devguyio) [inline pkg/common/consumer/consumer_handler.go:143]: What will happen when the delivery retry spec is longer than the timeout? I feel this this will override it .

File: pkg/common/consumer/consumer_handler.go [hunk 5]
```diff
@@ -113,14 +124,25 @@ func (consumer *SaramaConsumerHandler) ConsumeClaim(session sarama.ConsumerGroup
...
 		}
 
-		// Don't use the session context since it is closed before messages are drained.
-		// Handle must finish before the session timeout.
-		mustMark, err := consumer.handler.Handle(context.Background(), message)
+		// Preemptively interrupt processing messages if the session is closed.
+		// Processing all messages from the buffered channel can take a long time,
+		// potentially exceeding the session timeout, leading to duplicate events.
+		if sessionClosed(session) {
+			consumer.logger.Infof("Session closed for %s/%d. Exiting ConsumeClaim ", claim.Topic(), claim.Partition())
```
[the remark this answers is not in the document]
Comment (lionelvillard) [reply pkg/common/consumer/consumer_handler.go:135]: here info is fine. It's low traffic.

File: pkg/common/consumer/consumer_handler.go (hunk 4 above)
Comment (matzew) [reply pkg/common/consumer/consumer_handler.go:143]: should that perhaps than be included in the math for https://github.com/knative-sandbox/eventing-kafka/pull/659/files#diff-318b63710b5768647bfeb5b9bca7a04b80f3a8388439a6b8bc50eddfb8fed8e7R69 ?

Comment (lionelvillard) [reply pkg/common/consumer/consumer_handler.go:143]: KafkaSource does not retry... so yes seems like it's not the right place to do that

File: pkg/common/consumer/consumer_handler.go (hunk 2 above)
Comment (lionelvillard) [reply pkg/common/consumer/consumer_handler.go:168]: TIL... thanks!

File: pkg/common/consumer/consumer_handler.go (hunk 3 above)
Comment (lionelvillard) [reply pkg/common/consumer/consumer_handler.go:131]: No specific reason.

File: pkg/common/consumer/consumer_handler.go [hunk 6]
```diff
@@ -52,12 +53,32 @@ func WithSaramaConsumerLifecycleListener(listener SaramaConsumerLifecycleListene
 	}
 }
 
+// WithInflightRequestInterrupt configures the request timeout. Default is set to 60s.
```
Comment (matzew) [inline pkg/common/consumer/consumer_handler.go:56]: wrong comment `WithInflightRequestInterrupt` for the time out

Comment (lionelvillard) [reply pkg/common/consumer/consumer_handler.go:56]: you are fast!

**Comment by lionelvillard** [comment]
Credit to @devguyio for removing the timeout on all requests in ConsumeClaim. It's up to the handlers to set a timeout if they want.

File: pkg/common/consumer/consumer_handler.go [hunk 7]
```diff
@@ -52,12 +53,22 @@ func WithSaramaConsumerLifecycleListener(listener SaramaConsumerLifecycleListene
 	}
 }
 
+// WithTimeout configures the request timeout. Default is set to 60s.
+func WithTimeout(timeout time.Duration) SaramaConsumerHandlerOption {
```
Comment (matzew) [inline pkg/common/consumer/consumer_handler.go:57]: where exactly is that called / used ?

File: pkg/common/consumer/consumer_handler.go [hunk 8]
```diff
@@ -72,6 +83,7 @@ func NewConsumerHandler(logger *zap.SugaredLogger, handler KafkaConsumerHandler,
 	sch := SaramaConsumerHandler{
 		handler:           handler,
 		lifecycleListener: noopSaramaConsumerLifecycleListener{},
+		timeout:           60 * time.Second, // default rebalance timeout
```
Comment (matzew) [inline pkg/common/consumer/consumer_handler.go:86]: default... - it's more hard coded, atm - right?

File: pkg/common/consumer/consumer_handler.go [hunk 9]
```diff
@@ -108,24 +120,50 @@ func (consumer *SaramaConsumerHandler) Cleanup(session sarama.ConsumerGroupSessi
 func (consumer *SaramaConsumerHandler) ConsumeClaim(session sarama.ConsumerGroupSession, claim sarama.ConsumerGroupClaim) error {
 	consumer.logger.Infow(fmt.Sprintf("Starting partition consumer, topic: %s, partition: %d, initialOffset: %d", claim.Topic(), claim.Partition(), claim.InitialOffset()), zap.String("ConsumeGroup", consumer.handler.GetConsumerGroup()))
 	consumer.handler.SetReady(claim.Partition(), true)
+	c := make(chan bool)
```
Comment (matzew) [inline pkg/common/consumer/consumer_handler.go:123]: `c` as in `channel` ?

File: pkg/common/consumer/consumer_handler.go [hunk 10]
```diff
@@ -108,24 +120,50 @@ func (consumer *SaramaConsumerHandler) Cleanup(session sarama.ConsumerGroupSessi
...
-		mustMark, err := consumer.handler.Handle(context.Background(), message)
+		// Preemptively interrupt processing messages if the session is closed.
+		// Processing all messages from the buffered channel can take a long time,
+		// potentially exceeding the session timeout, leading to duplicate events.
+		if session.Context().Err() != nil {
+			consumer.logger.Infof("Session closed for %s/%d. Exiting ConsumeClaim ", claim.Topic(), claim.Partition())
+			break
+		}
+
+		hctx, cancel := context.WithCancel(context.Background())
```
Comment (matzew) [inline pkg/common/consumer/consumer_handler.go:142]: `hctx` as in handler context?

File: pkg/common/consumer/consumer_handler.go [hunk 11]
```diff
@@ -108,24 +120,50 @@ func (consumer *SaramaConsumerHandler) Cleanup(session sarama.ConsumerGroupSessi
...
+		go func() {
+			mustMark, err := consumer.handler.Handle(hctx, message)
+
+			if err != nil {
```
Comment (matzew) [inline pkg/common/consumer/consumer_handler.go:146]: plesae see here for nested go routine: https://github.com/knative-sandbox/eventing-kafka/pull/659/files#diff-318b63710b5768647bfeb5b9bca7a04b80f3a8388439a6b8bc50eddfb8fed8e7R125-R128

Comment (devguyio) [reply pkg/common/consumer/consumer_handler.go:146]: That comment is about moving the whole processing in a separate routine, the expectation is that `ConsumeClaim` ideally should block and loop over `Messages` which is the case here, cause we're blocking still in the select on line 156

**Comment by devguyio** [comment]
@lionelvillard that looks good to me, on the backport #661 I added some comments to the select to explain the logic, so I think it'd be useful to have them here as well.

File: pkg/common/consumer/consumer_handler.go (hunk 7 above)
Comment (devguyio) [reply pkg/common/consumer/consumer_handler.go:57]: I believe that's up for us to use it when composing the factory function `NewConsumerHandler` to override the default 60s. Can happen on a later PR though.

File: pkg/common/consumer/consumer_handler.go (hunk 8 above)
Comment (devguyio) [reply pkg/common/consumer/consumer_handler.go:86]: can be overridden by composing the factory function `NewConsumerHandler` with `WithTimeout` option .

File: pkg/common/consumer/consumer_handler.go (hunk 10 above)
Comment (devguyio) [reply pkg/common/consumer/consumer_handler.go:142]: yep

File: pkg/common/consumer/consumer_handler.go (hunk 9 above)
Comment (devguyio) [reply pkg/common/consumer/consumer_handler.go:123]: yep

Comment (lionelvillard) [reply pkg/common/consumer/consumer_handler.go:123]: @devguyio?  :-)

**Comment by lionelvillard** [comment]
/hold

seeing missing events

File: pkg/common/consumer/consumer_handler.go (hunk 9 above)
Comment (travis-minke-sap) [reply pkg/common/consumer/consumer_handler.go:123]: just my 2 cents (feel free to ignore : ) but I tend to agree with @matzew and try to avoid these short variable names ("c", "ce", "hctx", "f", "sch", etc).   It just requires more mental energy when reading the code to remember what they refer to rather than if they were spelled out (stopChan, checkedEntry, etc...).

File: pkg/common/consumer/consumer_handler.go [hunk 12]
```diff
@@ -108,24 +120,58 @@ func (consumer *SaramaConsumerHandler) Cleanup(session sarama.ConsumerGroupSessi
...
+
 	// NOTE:
 	// Do not move the code below to a goroutine.
 	// The `ConsumeClaim` itself is called within a goroutine, see:
 	// https://github.com/Shopify/sarama/blob/master/consumer_group.go#L27-L29
 	for message := range claim.Messages() {
-
 		if ce := consumer.logger.Desugar().Check(zap.DebugLevel, "debugging"); ce != nil {
 			consumer.logger.Debugw("Message claimed", zap.String("topic", message.Topic), zap.Binary("value", message.Value))
 		}
```
Comment (travis-minke-sap) [inline pkg/common/consumer/consumer_handler.go:132]: I realize this is pre-existing code (not part of this PR) but fwiw... the distributed channel has the following log which presents a readable version of the event...

```
	// Debug Log Kafka ConsumerMessage
	if h.Logger.Core().Enabled(zap.DebugLevel) {
		// Checked Logging Level First To Avoid Calling StringifyHeaderPtrs In Production
		h.Logger.Debug("Consuming Kafka Message",
			zap.Any("Headers", kafkasarama.StringifyHeaderPtrs(consumerMessage.Headers)), // Log human-readable strings, not base64
			zap.ByteString("Key", consumerMessage.Key),
			zap.ByteString("Value", consumerMessage.Value),
			zap.String("Topic", consumerMessage.Topic),
			zap.Int32("Partition", consumerMessage.Partition),
			zap.Int64("Offset", consumerMessage.Offset))
	}
```

Comment (lionelvillard) [reply pkg/common/consumer/consumer_handler.go:132]: there is still time to make changes :-) Thanks @travis-minke-sap !

Comment (devguyio) [reply pkg/common/consumer/consumer_handler.go:132]: Thanks! yeah that's much better, there're other parts in the channel that does almost exactly the same logging. and I think you meant `Debugw` not `Debug` right?

Comment (lionelvillard) [reply pkg/common/consumer/consumer_handler.go:143]: done.

Comment (lionelvillard) [reply pkg/common/consumer/consumer_handler.go:143]: I used Debugw

**Comment by lionelvillard** [comment]
/unhold

the missing events problem may be a red herring.
