### PR TITLE
[scheduler] Compact vreplicas

### LINKED ISSUE #699: [scheduler] mtadapters may not scale down
**Describe the bug**
The scheduler does not reassign vreplicas to "lower" pods  (ie: with a lower ordinal), preventing the autoscaler to scale down the mtadapter. 

 **Expected behavior**
The mtadapter should be able to scale down when there are unused pods.

 **To Reproduce**
Steps to reproduce the behavior.
Create 1 KafkaSource CR and scale it to 150. In knative-eventing, observe 2 adapter replicas. Create a second KafkaSource CR. Scale down the first KafkaSource CR to 1. The total number of vreplicas is now 2, spread across the 2 adapter replicas. In theory only one adapter is needed. 

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

### PR DESCRIPTION
**Pull request by lionelvillard**
Fixes #699

## Proposed Changes

- The statefulset autoscaler now attempts to compact vreplicas (MaxFillUp strategy only)
-
-

**Release Note**

```release-note
🎁 The multi-tenant KafkaSource controller periodically attempts to relocate KafkaSource consumers to Statefulset pods with a lower ordinal
```

**Docs**

### CODE REVIEW

**Comment by aavarghese** [comment]
/lgtm /approve
Tried it out - all good!!

**Review by aavarghese — APPROVED** [review]

File: pkg/source/reconciler/mtsource/controller.go [hunk 1]
```diff
@@ -73,7 +81,53 @@ func NewController(
...
+		after := before.DeepCopy()
+
+		bp := after.GetPlacements()
+		ap := make([]duckv1alpha1.Placement, 0, len(bp)-1)
+		for _, p := range bp {
+			if p.PodName != from.PodName {
+				ap = append(ap, p)
+			}
+		}
+		after.Status.Placement = ap
```
Comment (steven0711dong) [inline pkg/source/reconciler/mtsource/controller.go:102]: 1. If we have a Kafka source on the last pod with one replica and this Kafka source has only one vreplica. What would happen? 
2. Once we remove the replica from the last pod, what if KEDA scaled the replica again? Almost seems like KEDA and this logic works in the opposite direction.

Comment (lionelvillard) [reply pkg/source/reconciler/mtsource/controller.go:102]: 1. if there are enough free capacity before the last pod, the vreplica will be moved
2. Keda is about increasing/decreasing the number of vreplicas. But I see what you mean. When scaling down, the vreplicas closest to the last pod are first removed (after your fix) so from this PoV Keda and this PR are working in the same direction.

File: pkg/common/scheduler/statefulset/autoscaler.go [hunk 2]
```diff
@@ -155,7 +162,60 @@ func (a *autoscaler) doautoscale(ctx context.Context, attemptScaleDown bool, pen
...
+		return err
+	}
+
+	for _, vpod := range vpods {
+		placements := vpod.GetPlacements()
+		for _, placement := range placements {
+			ordinal := ordinalFromPodName(placement.PodName)
+
+			if ordinal == s.lastOrdinal {
+				a.logger.Infow("evicting vreplica(s)", zap.String("podname", placement.PodName), zap.Int("vreplicas", int(placement.VReplicas)))
```
Comment (steven0711dong) [inline pkg/common/scheduler/statefulset/autoscaler.go:211]: please also log the name of the Kafka source being evicted as well.

Comment (lionelvillard) [reply pkg/common/scheduler/statefulset/autoscaler.go]: done!

File: pkg/common/scheduler/statefulset/autoscaler.go [hunk 3]
```diff
@@ -42,9 +43,11 @@ type Autoscaler interface {
 type autoscaler struct {
 	statefulSetClient clientappsv1.StatefulSetInterface
 	statefulSetName   string
+	vpodLister        scheduler.VPodLister
 	logger            *zap.SugaredLogger
 	stateAccessor     stateAccessor
 	trigger           chan int32
+	evict             scheduler.Evictor
```
[the remark this answers is not in the document]
Comment (lionelvillard) [reply pkg/common/scheduler/statefulset/autoscaler.go]: done.

File: pkg/common/scheduler/scheduler.go [hunk 4]
```diff
@@ -31,6 +31,9 @@ var (
 // VPodLister is the function signature for returning a list of VPods
 type VPodLister func() ([]VPod, error)
 
+// Evictor allows for vreplicas to be evicted
```
[the remark this answers is not in the document]
Comment (lionelvillard) [reply pkg/common/scheduler/scheduler.go]: I added an example of how this can be used. Thanks!

**Review by aavarghese — APPROVED** [review]
/lgtm
