### PR TITLE
Consolidated channel watch config kafka

### LINKED ISSUE #393: Editing `config-kafka` causes consolidated channel controller to panic and block forever
**Describe the bug**
2 problems:

1. When there's an existing Kafka Channel, it can't be deleted when I modify config-kafka.
- Create a channel
- Modify `config-kafka`
- Try deleting the channel
- Controller panics

2. `consumerGroupWatcher` is stuck in termination
- Create a channel
- Modify `config-kafka`
- `consumerGroupWatcher.terminate()` is stuck (it has some mutexes etc)

 **Expected behavior**

 **To Reproduce**
Steps to reproduce the behavior.

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

### PR DESCRIPTION
**Pull request by aliok**
Fixes #393

## Proposed Changes

- Replace hardcoded `config-kafka` string with proper constant
- Fix a panic: null check `consumerGroupWatcher`
- Fix a block: `consumerGroupWatcher.terminate()` doesn't block forever anymore

Please review commit by commit.

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

File: pkg/common/constants/constants.go [hunk 1]
```diff
@@ -23,8 +23,14 @@ const (
 	DefaultReplicationFactor = 1
 
 	// The name of the configmap used to hold eventing-kafka settings
-	SettingsConfigMapName          = "config-kafka"
+	SettingsConfigMapName = "config-kafka"
```
Comment (matzew) [inline pkg/common/constants/constants.go:26]: what a weird name :-)  `Settings...`, but hey

File: pkg/common/constants/constants.go [hunk 2]
```diff
@@ -23,8 +23,14 @@ const (
...
+
+	// Mount path of the configmap used to hold eventing-kafka settings
+	SettingsConfigMapMountPath = "/etc/config-kafka"
```
Comment (matzew) [inline pkg/common/constants/constants.go:29]: should we leverage here the name of the `SettingsConfigMapName` ? 

well, could be too much :smile:

File: pkg/channel/consolidated/reconciler/controller/kafkachannel.go [hunk 3]
```diff
@@ -616,6 +618,8 @@ func (r *Reconciler) FinalizeKind(ctx context.Context, kc *v1beta1.KafkaChannel)
 			return err
 		}
 	}
-	r.consumerGroupWatcher.Forget(string(kc.ObjectMeta.UID))
+	if r.consumerGroupWatcher != nil {
+		r.consumerGroupWatcher.Forget(string(kc.ObjectMeta.UID))
+	}
```
Comment (matzew) [inline pkg/channel/consolidated/reconciler/controller/kafkachannel.go:623]: wat is that?

File: pkg/channel/consolidated/reconciler/controller/kafkachannel.go [hunk 4]
```diff
@@ -600,7 +600,9 @@ func (r *Reconciler) updateKafkaConfig(ctx context.Context, configMap *corev1.Co
 	}
 
 	if r.consumerGroupWatcher != nil {
+		logger.Info("Terminating consumer group watcher")
```
Comment (matzew) [inline pkg/channel/consolidated/reconciler/controller/kafkachannel.go:603]: `terminating` ? Instead of capital `T` ?

File: pkg/channel/consolidated/reconciler/controller/kafkachannel.go [hunk 5]
```diff
@@ -600,7 +600,9 @@ func (r *Reconciler) updateKafkaConfig(ctx context.Context, configMap *corev1.Co
...
 		r.consumerGroupWatcher.Terminate()
+		logger.Info("Terminated consumer group watcher")
```
Comment (matzew) [inline pkg/channel/consolidated/reconciler/controller/kafkachannel.go:605]: `terminating` ? Instead of capital `T` ?

File: pkg/common/constants/constants.go (hunk 2 above)
Comment (aliok) [reply pkg/common/constants/constants.go:29]: yeah, thanks!

File: pkg/channel/consolidated/reconciler/controller/kafkachannel.go (hunk 3 above)
Comment (aliok) [reply pkg/channel/consolidated/reconciler/controller/kafkachannel.go:623]: `consumerGroupWatcher` becomes nil when the bootstrap server is unreachable. Like:
1. Have `config-kafka` has proper bootstrap server
2. Create a Kafka channel
3. Change bootstrap server in `config-kafka` to nonsense
4. `consumerGroupWatcher` becomes nil
5. Couldn't delete Kafka channel afterwards --> panic

This change adds a null check that's all

Comment (matzew) [reply pkg/channel/consolidated/reconciler/controller/kafkachannel.go:623]: @aliok let's capture that in the comments?  Please ? :smile:
