### PR TITLE
fix-reconfigure-and-reconciliation-issues

### LINKED ISSUE #794: [Distributed KafkaChannel] Dispatcher Reconciliation & Reconfigure Lifecycle Problems
**Describe the bug**
There are a couple problems with the Dispatcher's "controller" which is watching KafkaChannels in order to start/stop Kafka ConsumerGroups...

1. The reconciler does not requeue upon reconciliation errors so subscribers can become "stuck" in a bad state until the KafkaChannel is changed.
2. An existing kafkachannel can be put into a not ready state by a bad Reconfigure (Kafka Secret change) and is not returned when the Secret is fixed.
3. A "stopped" subscription would unintentionally be restarted by a Reconfigure (Kafka Secret Change)

 **Expected behavior**
1. The reconciler should return errors to force a requeue of the KafkaChannel in an attempt to resolve the problem.
2. A Subscription is returned to READY state after a bad Kafka Secret change is corrected.
3. A "stoped" subscription should not be affected by a Reconfigure (Kafka Secret Change)

 **To Reproduce**
1. Create a KafkaChannel with a Subscription.  Change the Kafka Secret to invalid values which will trigger a reconfigure which will result in the Subscription being "MarkedNotReadyByChannel".  Verify the reconciler requeues the KafkaChannel and keeps trying (backoff)
2. Create a KafkaChannel with a Subscription.  Change the Kafka Secret to invalid values which will trigger a reconfigure which will result in the Subscription being "MarkedNotReadyByChannel".  Fix the Kafka Secret back to valid values and notice that the Subscription is not returned to a READY state.
3. Really hard to reproduce now since the "Pause" capability is not in place - would have to catch a ResetOffset at just the right moment.  

 **Knative release version**
/main

 **Additional context**
This code needs to respect the control-protocol messaging used to Stop/Start Consumer Groups for the ResetOffset (and eventually the Pause) features.  Subscriptions which are "stopped" should not be restarted as part of a Reconfigure (Kafka Secret Change)

### PR DESCRIPTION
**Pull request by travis-minke-sap**
Fixes #794 

## Proposed Changes

- 🧽  Restructure Dispatcher main() to create Controller prior to SecretWatcher.
- 🧽  Change Dispatcher's SecretObserver to be a factory capable of requeueing KafkaChannels.
- 🧽  Add util function to convert from GroupId back to Subscription.UID.
- 🧽  Return errors from Dispatcher Controller Reconcile() to requeue on failure.
- 🧽  Create new ReconfigureError type to contain the failed ConsumerGroup IDs
- 🧽  Dispatcher.SecretChanged() should handle ReconfigureErrors by removing failed ConsumerGroups from Dispatcher.subscribers so that the next reconcile will not ignore them (as being previously closed)
- 🐛 Dispatcher.Reconfigure() bug fixed so that "paused" (stopped) aren't restarted.
- 🧽  Dispatcher.Reconfigure() tracks failed ConsumerGroup IDs and returns new ReconfigureError type.
- 🧽  Removed unneeded DispatcherConfig.SubscriberSpecs

**Release Note**

```release-note
Distributed KafkaChannel Dispatcher will now re-queue KafkaChannels after failed reconciliation which will improve various failure recovery scenarios, but could consume CPU resources if reconciliation is blocked by underlying system issues (bad Kafka Secret config, etc.)
```

Holding for further testing...
/hold

### CODE REVIEW

File: cmd/channel/distributed/dispatcher/main.go [hunk 1]
```diff
@@ -219,21 +210,35 @@ func flush(logger *zap.Logger) {
...
+		// Ignore Startup Scenario Where Dispatcher Reference Might Be Nil
+		if dispatcher == nil {
+			logger.Debug("Dispatcher is nil during call to secretObserver; ignoring changes")
+			return
+		}
+
+		// Signal The Dispatcher To Recreate Kafka Config And Reconnect All Current ConsumerGroups
+		dispatcher.SecretChanged(ctx, secret)
+
+		// Requeue The KafkaChannel To Fix Any "Stuck" Subscriptions From A Prior Bad Kafka Secret
```
Comment (eric-sap) [inline cmd/channel/distributed/dispatcher/main.go:235]: This is really "from any error trying to start the ConsumerGroups," right?  Seems disingenuinely precise to call this out explicitly (perhaps "e.g." or just a more general reason?)

File: cmd/channel/distributed/dispatcher/main.go [hunk 2]
```diff
@@ -219,21 +210,35 @@ func flush(logger *zap.Logger) {
...
+		channelNamespace, channelName, err := cache.SplitMetaNamespaceKey(channelKey)
+		if err != nil {
+			logger.Error("Invalid KafkaChannel Key", zap.String("ChannelKey", channelKey), zap.Error(err))
+		} else {
+			logger.Debug("Requeue-ing KafkaChannel due to Kafka Secret change", zap.String("ChannelKey", channelKey))
+			kcController.EnqueueKey(types.NamespacedName{Namespace: channelNamespace, Name: channelName})
+		}
```
Comment (eric-sap) [inline cmd/channel/distributed/dispatcher/main.go:242]: Instead of passing in the channelKey and doing this SplitMetaNamespaceKey every time (with the error handling), would it be better to just pass in the NamespacedName to NewSecretObserver?  If I'm not mistaken it will never change during the life of the pod and would make this function less complicated.

File: pkg/channel/distributed/common/kafka/util/util.go [hunk 3]
```diff
@@ -20,17 +20,26 @@ import (
 	"fmt"
 	"strings"
 
+	"k8s.io/apimachinery/pkg/types"
+
 	"knative.dev/eventing-kafka/pkg/channel/distributed/common/kafka/constants"
 )
 
+const GroupIdPrefix = "kafka"
```
Comment (eric-sap) [inline pkg/channel/distributed/common/kafka/util/util.go:28]: Seems like the prefix is "kafka." - why not include the dot here instead of having to add it both in GroupId() and Uid() and the tests ?

File: pkg/common/consumer/consumer_manager.go [hunk 4]
```diff
@@ -120,6 +120,20 @@ type kafkaConsumerGroupManagerImpl struct {
...
 
+// ReconfigureError is a custom error type returned by the Reconfigure() function.
+type ReconfigureError struct {
+	MultiError error    // A MultiError with all ConsumerGroup failures.
+	GroupIds   []string // The ConsumerGroup IDs which failed to stop/start.
+}
+
+// Error implements the golang error interface.
+func (r *ReconfigureError) Error() string {
+	return r.MultiError.Error()
```
Comment (eric-sap) [inline pkg/common/consumer/consumer_manager.go:131]: Is this okay if r.MultiError is nil?  It won't be in the code that uses it but since this is an exported struct it might be good to check.

**Review by eric-sap — COMMENTED** [review]
Some minor questions

File: pkg/common/consumer/consumer_manager.go (hunk 4 above)
Comment (travis-minke-sap) [reply pkg/common/consumer/consumer_manager.go:131]: No, good call - I was thinking of returning the GroupIDs in the error string anyway - should be made more robust - I'll fix it!

File: pkg/channel/distributed/common/kafka/util/util.go (hunk 3 above)
Comment (travis-minke-sap) [reply pkg/channel/distributed/common/kafka/util/util.go:28]: I originally had it that way but felt the "." was a "separator" instead of the prefix - I think it's ok as is.

File: cmd/channel/distributed/dispatcher/main.go (hunk 2 above)
Comment (travis-minke-sap) [reply cmd/channel/distributed/dispatcher/main.go:242]: You're right that the `channelKey` value is "fixed" for the Dispatcher instance (since it's only ever dealing with one KafkaChannel) but I'd rather not pass in the NamespacedName since it's only used here, etc...

File: cmd/channel/distributed/dispatcher/main.go (hunk 1 above)
Comment (travis-minke-sap) [reply cmd/channel/distributed/dispatcher/main.go:235]: Yeah, that's true - will adjust the comment language - thanks
