### PR TITLE
start to remove vreplicas from biggest ordinal

### LINKED ISSUE #628: [mtsource] Remove vreplicas starting from adapter pods with the biggest ordinal
**Describe the bug**
When KEDA scales vreplicas down, the extra vreplicas were removed from the wrong adapter pod. 

 **Expected behavior**
The extra vreplicas should be removed from adapter pods with the biggest ordinal first 

 **To Reproduce**
Create a Kafka source that spans over 2 pods and then stop sending events to the topic, when KEDA scales the vreplica back to 1, you will see the Kafka source ends up on the adapter pod that has the biggest ordinal number. 

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

### PR DESCRIPTION
**Pull request by steven0711dong**
close https://github.com/knative-sandbox/eventing-kafka/issues/628

## Proposed Changes

-
-
-

**Release Note**

```release-note

```

**Docs**

### CODE REVIEW

File: pkg/source/reconciler/mtsource/kafkasource.go [hunk 1]
```diff
@@ -108,7 +110,11 @@ func (r *Reconciler) ReconcileKind(ctx context.Context, src *v1beta1.KafkaSource
 
 func (r *Reconciler) reconcileMTReceiveAdapter(src *v1beta1.KafkaSource) error {
 	placements, err := r.scheduler.Schedule(src)
-
+	sort.SliceStable(placements, func(i int, j int) bool {
+		podIOrdinal, _ := strconv.Atoi(placements[i].PodName[len(placements[i].PodName)-1:])
+		podJOrdinal, _ := strconv.Atoi(placements[j].PodName[len(placements[j].PodName)-1:])
+		return podIOrdinal < podJOrdinal
+	})
```
Comment (lionelvillard) [inline pkg/source/reconciler/mtsource/kafkasource.go:117]: `Schedule` should return a sorted list on placements as it relies on it.

Comment (steven0711dong) [reply pkg/source/reconciler/mtsource/kafkasource.go:117]: The current logic of addVReplica is adding `vreplicas` to existing pod, then allocate additional pods. In case existing pod is not a sequence, it's possible scheduler adds `vreplicas` to a pod that's in between existing pods. In this scenario, Schedule won't return a sorted list.

File: pkg/common/scheduler/scheduler.go [hunk 2]
```diff
@@ -35,6 +35,7 @@ type VPodLister func() ([]VPod, error)
 type Scheduler interface {
 	// Schedule computes the new set of placements for vpod.
 	Schedule(vpod VPod) ([]duckv1alpha1.Placement, error)
+	ScheduleVPod(vpod VPod) ([]duckv1alpha1.Placement, error)
```
Comment (lionelvillard) [inline pkg/common/scheduler/scheduler.go:38]: Let's keep the interface minimal. No need to expose ScheduleVPod

Comment (steven0711dong) [reply pkg/common/scheduler/scheduler.go:38]: I tried to change `ScheduleVPod` to `scheduleVPod` but there is compiler error complaining cannot use `StatefulSetScheduler` as interface Scheduler. I think it has something to do with `StatefulSetScheduler` and Scheduler interface being defined in different package so we need to make `scheduleVPod` exported.

Comment (lionelvillard) [reply pkg/common/scheduler/scheduler.go:38]: I suggest to remove `ScheduleVPod` altogether from the interface.

Comment (steven0711dong) [reply pkg/common/scheduler/scheduler.go:38]: If we remove ScheduleVPod, how do you propose to sort the placements?

**Review by lionelvillard — APPROVED** [review]
